extern const GeoLayout lll_area_1_geo[];
extern const GeoLayout lll_area_1[];
extern const Collision lll_area_1_collision[];
extern const MacroObject lll_area_1_macro_objs[];
extern Lights1 lll_dl_f3dlite_material_lights;
extern Vtx lll_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx lll_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_lll_dl_f3dlite_material[];
extern Gfx mat_revert_lll_dl_f3dlite_material[];
extern Gfx lll_dl_Plane_mesh_layer_1_with_revert[];
