extern const GeoLayout lll_area_1_geo[];
extern const GeoLayout lll_area_1[];
extern const Collision lll_area_1_collision[];
extern const MacroObject lll_area_1_macro_objs[];
extern const GeoLayout lll_area_2_geo[];
extern const GeoLayout lll_area_2[];
extern const Collision lll_area_2_collision[];
extern const MacroObject lll_area_2_macro_objs[];
extern Lights1 lll_dl_pole1_lights;
extern u8 lll_dl_MARIOKART64_1A6956B5_0_2_all_ci4[];
extern u8 lll_dl_MARIOKART64_1A6956B5_0_2_all_pal_rgba16[];
extern u8 lll_dl_quartz_block_bottom__5__ci8[];
extern u8 lll_dl_quartz_block_bottom__5__pal_rgba16[];
extern u8 lll_dl_lava1_ci4[];
extern u8 lll_dl_lava1_pal_rgba16[];
extern u8 lll_dl_netherrack__11__ci8[];
extern u8 lll_dl_netherrack__11__pal_rgba16[];
extern u8 lll_dl_yogan01_ci8[];
extern u8 lll_dl_yogan01_pal_rgba16[];
extern u8 lll_dl_volcanplateforme_ci4[];
extern u8 lll_dl_volcanplateforme_pal_rgba16[];
extern Vtx lll_dl_pole_mesh_layer_1_vtx_0[21];
extern Gfx lll_dl_pole_mesh_layer_1_tri_0[];
extern Vtx lll_dl_pole2_mesh_layer_1_vtx_0[21];
extern Gfx lll_dl_pole2_mesh_layer_1_tri_0[];
extern Vtx lll_dl_pole3_mesh_layer_1_vtx_0[21];
extern Gfx lll_dl_pole3_mesh_layer_1_tri_0[];
extern Vtx lll_dl_pole4_mesh_layer_1_vtx_0[21];
extern Gfx lll_dl_pole4_mesh_layer_1_tri_0[];
extern Vtx lll_dl_volcano_mesh_layer_1_vtx_0[841];
extern Gfx lll_dl_volcano_mesh_layer_1_tri_0[];
extern Vtx lll_dl_volcano_mesh_layer_1_vtx_1[53];
extern Gfx lll_dl_volcano_mesh_layer_1_tri_1[];
extern Vtx lll_dl_volcano_mesh_layer_1_vtx_2[199];
extern Gfx lll_dl_volcano_mesh_layer_1_tri_2[];
extern Vtx lll_dl_volcano_mesh_layer_1_vtx_3[39];
extern Gfx lll_dl_volcano_mesh_layer_1_tri_3[];
extern Vtx lll_dl_volcano_mesh_layer_1_vtx_4[236];
extern Gfx lll_dl_volcano_mesh_layer_1_tri_4[];
extern Vtx lll_dl_arena_mesh_layer_1_vtx_0[529];
extern Gfx lll_dl_arena_mesh_layer_1_tri_0[];
extern Vtx lll_dl_arena_mesh_layer_1_vtx_1[57];
extern Gfx lll_dl_arena_mesh_layer_1_tri_1[];
extern Vtx lll_dl_arena_mesh_layer_1_vtx_2[8];
extern Gfx lll_dl_arena_mesh_layer_1_tri_2[];
extern Vtx lll_dl_arena_mesh_layer_1_vtx_3[16];
extern Gfx lll_dl_arena_mesh_layer_1_tri_3[];
extern Gfx mat_lll_dl_pole1[];
extern Gfx mat_revert_lll_dl_pole1[];
extern Gfx mat_lll_dl_roche2_layer1[];
extern Gfx mat_revert_lll_dl_roche2_layer1[];
extern Gfx mat_lll_dl_lava[];
extern Gfx mat_revert_lll_dl_lava[];
extern Gfx mat_lll_dl_volcan_layer1[];
extern Gfx mat_revert_lll_dl_volcan_layer1[];
extern Gfx mat_lll_dl_lava_chute_layer1[];
extern Gfx mat_revert_lll_dl_lava_chute_layer1[];
extern Gfx mat_lll_dl_plateforme_layer1[];
extern Gfx mat_revert_lll_dl_plateforme_layer1[];
extern Gfx mat_lll_dl_roche2_001_layer1[];
extern Gfx mat_revert_lll_dl_roche2_001_layer1[];
extern Gfx lll_dl_pole_mesh_layer_1[];
extern Gfx lll_dl_pole2_mesh_layer_1[];
extern Gfx lll_dl_pole3_mesh_layer_1[];
extern Gfx lll_dl_pole4_mesh_layer_1[];
extern Gfx lll_dl_volcano_mesh_layer_1_with_revert[];
extern Gfx lll_dl_arena_mesh_layer_1_with_revert[];
